Útskýringar eru í Kernel bible 2 ef þig þyrstir í aukaefni

<br>
Hér kemur bara eitthvað random dæmi, á að virkar fyrir

$$f_{\theta}: \mathbb{R}^{n} \rightarrow \mathbb{R}^{m}$$

In [2]:
include("NN.jl")

model = Chain(Dense(784 => 2, sigmoid), Dense(2 => 10)) # W_2[1x2](W_1[2x1]x[1]+b_1[2x1])+b_2[1]

x1 = load_MNIST()[1][:,1];
x2 = load_MNIST()[1][:,2];

In [3]:
function Df(model, x)
    # x: single datapoint
    m = length(model(x))
    k = sum(length, Flux.params(model)) # Total amount of params

    # Þetta anonymous function reiknar gradient fyrir hvert function í outputinu frá 1:m
    jac = (fi) -> Flux.jacobian(() -> model(x)[fi],Flux.params(model)) # anonymous function

    # Skilgreini tómt Jacobian fylki
    Jacob = zeros(k,m)

    for func_i = 1:m
        current_col = []
        for param_i = 1:length(Flux.params(model))
            push!(current_col, jac(func_i)[Flux.params(model)[param_i]]) # Fyrir hvern parametra W1, B1, W2...
        end
        current_col = collect(Iterators.flatten(current_col)) # Flatten, flet allt
        # --- Spurning hvort hægt sé að gera þetta skilvirkara?
        # --- Held samt að Iterators pakkinn eigi að vera nokkuð skilvirkur

        Jacob[:, func_i] .= current_col # geri current_col að næsta dálka vigri jacobian
    end

    return Jacob # Þetta er Df fylkið í bilblíunni
end

function kernel(model, x)
    # x: dataset
    N = length(x)
    m = length(model(x[1]))  # Number of functions in the model output
    K = zeros(N*m, N*m)

    for i = 1:N
        for j = 1:N
            block = Df(model, x[i])' * Df(model, x[j])
            K[(i-1)*m+1:i*m, (j-1)*m+1:j*m] .= block
        end
    end

    return K
end

kernel (generic function with 2 methods)

In [4]:
x = [x1,x2]

K = kernel(model,x);
println("Kernel completed")

Kernel completed


In [5]:
using LinearAlgebra

# Check if K is ok
if K == K'
    println( "K is symmetric")
end

val = eigen(K).values
negVal = findall(x-> x < 0, val)

K is symmetric

Int64[]

In [29]:

using Flux
model = Chain(Dense(2=>),Dense(2=>2))|>f64

Flux.params(model)[1] .= ones(Float64,2,2)
Flux.params(model)[2] .= Float64.([1;0])
Flux.params(model)[3] .= ones(Float64,2,2)*2
Flux.params(model)[4] .= Float64.([0;1])

W1 = Flux.params(model)[1]
B1 = Flux.params(model)[2]
W2 = Flux.params(model)[3]
B2 = Flux.params(model)[4]



# for i in 1:4 
#     display(Flux.params(model)[i])
# end

t1 = Float64.([1;0])
t2 = Float64.([2;1])



function df_1(W1,B1,W2,B2,t)
    df_dθ1 = Float64.([W2[1,1]*t[1]; W2[2,1]*t[1]])
    return df_dθ1
end
function df_2(W1,B1,W2,B2,t)
    df_dθ2 = Float64.([W2[1,2]*t[1]; W2[2,2]*t[1]])
    return df_dθ2
end
function df_3(W1,B1,W2,B2,t)
    df_dθ3 = Float64.([W2[1,1]*t[2]; W2[2,1]*t[2]])
    return df_dθ3
end
function df_4(W1,B1,W2,B2,t)
    df_dθ4 = Float64.([W2[1,2]*t[2]; W2[2,2]*t[2]])
    return df_dθ4
end
function df_5(W1,B1,W2,B2,t)
    df_dθ5 = Float64.([2*W2[1,1];2*W2[2,1]])
    return df_dθ5
end
function df_6(W1,B1,W2,B2,t)
    df_dθ6 = Float64.([2*W2[1,2];2*W2[2,2]])
    return df_dθ6
end
function df_7(W1,B1,W2,B2,t)
    df_dθ7 = Float64.([W1[1,1]*t[1]+2*B1[1]+W1[1,2]*t[2];0])
    return df_dθ7
end
function df_8(W1,B1,W2,B2,t)
    df_dθ8 = Float64.([0;W1[1,1]*t[1]+2*B1[1]+W1[1,2]*t[2]])
    return df_dθ8
end
function df_9(W1,B1,W2,B2,t)
    df_dθ9 = Float64.([W1[2,1]*t[1]+2*B1[2]+W1[2,2]*t[2];0])
    return df_dθ9
end
function df_10(W1,B1,W2,B2,t)
    df_dθ10 = Float64.([0;W1[2,1]*t[1]+2*B1[2]+W1[2,2]*t[2]])
    return df_dθ10
end
function df_11(W1,B1,W2,B2,t)
    df_dθ11 = Float64.([1;0])
    return df_dθ11
end
function df_12(W1,B1,W2,B2,t)
    df_dθ12 = Float64.([0;1])
    return df_dθ12
end

# Collect all the derivative functions in an array for easier iteration
dfs = [df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10, df_11, df_12]

# Initialize a structure to hold the results
results_t1 = zeros(Float64, 12, 2)
results_t2 = zeros(Float64, 12, 2)

# Compute derivatives for t1 and t2
for (i, df) in enumerate(dfs)
    results_t1[i, :] = df(W1, B1, W2, B2, t1)
    results_t2[i, :] = df(W1, B1, W2, B2, t2)
end

# block 11
K11 = results_t1'*results_t1

# block 12
K12 = results_t1'*results_t2

# block 21
K21 = results_t2'*results_t1

# block 22
K22 = results_t2'*results_t2

K = [K11 K12;K21 K22]

λ = eigen(K).values

myK = kernel(model, [t1,t2])
display(K)
display(myK)
display(λ)
display(eigen(myK).values)

4×4 Matrix{Float64}:
 51.0  40.0   67.0   48.0
 40.0  51.0   48.0   67.0
 67.0  48.0  107.0   72.0
 48.0  67.0   72.0  107.0

4×4 Matrix{Float64}:
 22.0  16.0  36.0  24.0
 16.0  22.0  24.0  36.0
 36.0  24.0  74.0  48.0
 24.0  36.0  48.0  74.0

4-element Vector{Float64}:
   0.5277949457557569
  11.86998741167935
  45.47220505424414
 258.1300125883204

4-element Vector{Float64}:
   0.3795006481866981
   6.76066630559778
  31.620499351813233
 153.23933369440206

2-element Vector{Float64}:
 6.0
 7.0