### Authors: Axel & Tristan


In [346]:
using Flux,CairoMakie,Zygote,LinearAlgebra,IterTools

In [347]:
function node_count(model)
    """Function checks how many nodes are in each layer
       Including  the input, ouput and hidden layers"""
    param(x)  = Flux.params(model)[x]
    n = []
    for i = 1:length(Flux.params(model))
        if i%2 != 0 # Check all weights in θ 
            ni = size(param(i))[2]
            push!(n,ni)                 
        end                             
    end

    """We also have to check the output layer specifically.  
       This is because there is not weight in θ associated with the output layer"""
    push!(n, length(param(length(Flux.params(model)))))
    return n
end


function norm_params(model)
    θ(x)  = Flux.params(model)[x]
    nNodes = node_count(model)

    i = 1
    for n = 1:length(nNodes)-1
        ni = nNodes[n]

        θ(i) .= θ(i) * 1/sqrt(ni)
        i += 1
        θ(i) .= θ(i) * 1/sqrt(ni)
        i += 1

    end
end


norm_params (generic function with 1 method)

In [294]:
# x1 = [0.4]
# x2 = [1.1]
# n1 = 10


# model = Chain(Dense(1,n1,sigmoid),Dense(n1,1))|>f64



# norm_params(model)

# ∇_x1 = gradient(()->model(x1)[1],Flux.params(model))
# ∇_x2 = gradient(()->model(x2)[1],Flux.params(model))

# n = 2
# m = 2
# K = zeros(m,n)
# K[1,1] = dot(∇_x1,∇_x1)
# K[2,2] = dot(∇_x2,∇_x2)
# K[1,2] = dot(∇_x1,∇_x2)
# K[2,1] = dot(∇_x2,∇_x1)

# K

# λ = eigen(K).values



In [348]:
x1 = [0.4]
x2 = [1.1]
n1 = 100000


model = Chain(Dense(1,n1,sigmoid),Dense(n1,1))
norm_params(model)


xR = range(-1,1,step=0.1)
xn = hcat(xR...)
∇_xn = []
Q = length(model)
N = length(xn)
for xi = 1:N
    ∇_i = gradient(()->model(xn[:,xi])[1],Flux.params(model))
    push!(∇_xn, ∇_i)
end

Kernel = zeros(N,N)
for m = 1:N
    for n = 1:N
    Kernel[m,n] = dot(∇_xn[m],∇_xn[n])
    end
end






Kernel
λ_t = eigen(Kernel).values


21-element Vector{Float64}:
     -0.1729997496898309
     -0.1302309576020151
     -0.0975426209876386
     -0.06564196056219931
     -0.05105226738243468
     -0.03940309204531814
     -0.022763451307821675
     -0.019587488651794466
     -0.018603394964443687
      0.007448610282778517
      ⋮
      0.02997697841932176
      0.04308533996532138
      0.05529410075375754
      0.06325114633996679
      0.08825945976058758
      0.13362789091176014
      0.17090612536104266
      0.9478494242062565
 525021.0032635985

In [349]:


# for ∇ in ∇_x1
#     println(∇)
# end

# ∇_x1[Flux.params(model)[4]]


P = length(Flux.params(model))
Ng = length(∇_xn)
∇_matrix = []
for i = 1:Ng
    ∇_col = []
    for j = 1:P-1
        param_grad = ∇_xn[i][Flux.params(model)[j]]
        push!(∇_col,param_grad)
    end
    push!(∇_matrix,∇_col)
end

∇_matrix

21-element Vector{Any}:
 Any[Float32[1.5325591f-7; -5.7432385f-6; … ; 5.8614514f-6; -1.7573741f-6;;], Float32[-1.5325591f-7, 5.7432385f-6, -4.017281f-6, -3.19669f-6, -1.8278462f-6, -7.2670396f-8, 4.9618607f-6, 4.0735144f-6, -2.3367445f-6, 5.20527f-6  …  -5.3804483f-6, 5.1123375f-6, 3.4617083f-6, 1.2558121f-6, 8.843795f-7, 3.5013995f-6, 2.6005297f-8, 3.8606213f-6, -5.8614514f-6, 1.7573741f-6], Float32[0.49907982 0.500844 … 0.5000564 0.50170505]]
 Any[Float32[1.3793041f-7; -5.168917f-6; … ; 5.275306f-6; -1.5816402f-6;;], Float32[-1.5325602f-7, 5.7432417f-6, -4.01729f-6, -3.1966904f-6, -1.8278462f-6, -7.2670495f-8, 4.9618607f-6, 4.073517f-6, -2.3367454f-6, 5.205275f-6  …  -5.3804497f-6, 5.1123384f-6, 3.4617112f-6, 1.2558152f-6, 8.8438f-7, 3.5014f-6, 2.6005347f-8, 3.860626f-6, -5.8614514f-6, 1.757378f-6], Float32[0.49917188 0.5007596 … 0.5000507 0.5015346]]
 Any[Float32[1.2260489f-7; -4.594596f-6; … ; 4.6891614f-6; -1.4059052f-6;;], Float32[-1.5325611f-7, 5.7432444f-6, -4.0172977f-6, -3.19

In [355]:
# Function to flatten
function flatten_gradients(grad_components)
    flat_grad = Float64[]
    for comp in grad_components
        # Flatten
        append!(flat_grad, comp[:])
    end
    return flat_grad
end


flat_grads = [flatten_gradients(∇) for ∇ in ∇_matrix]

flat_grads[1]

# Kernel = zeros(Float64, length(flat_grads), length(flat_grads))
# for i in 1:length(flat_grads)
#     for j in 1:length(flat_grads)
#         Kernel[i, j] = flat_grads[i]'*flat_grads[j]
#     end
# end

# Kernel

# λ = eigen(Kernel).values


300000-element Vector{Float64}:
  1.5325591107284708e-7
 -5.743238489230862e-6
  4.017280843982007e-6
  3.196689931428409e-6
  1.827846176638559e-6
  7.267039592306901e-8
 -4.961860668117879e-6
 -4.073514446645277e-6
  2.33674450100807e-6
 -5.20527009939542e-6
  ⋮
  0.49953946471214294
  0.5010673403739929
  0.5017957091331482
  0.49919593334198
  0.4994317591190338
  0.5015895962715149
  0.5012345314025879
  0.5000563859939575
  0.5017050504684448

In [353]:
function check_dim(x)
    """This function checks the appropriate  dimensions of input data"""
    if isa(x, Matrix)
        return size(x, 2)  # Returns the number of columns (width) of the matrix
    elseif isa(x, Vector)
        return 1  # Return 1 if it's a column vector
    else
        type = typeof(x)
        error("Input data type: $type is neither a matrix or column vector")
    end
end

function jac(model, x, f,param)
    """Gets the jacobian of a specific parameter"""
    jaco(f) = Flux.jacobian(() -> model(x)[f],Flux.params(model))
    return jaco(f)[Flux.params(model)[param]]
end

function Df(model, x)
    # x: single datapoint
    m = length(model(x))

    # Total amount of θ exluding final bias
    total_amount_of_θ = sum(length, Flux.params(model))  - length(Flux.params(model)[length(Flux.params(model))])

    # Skilgreini empty jacobian matrix
    Jacob = zeros(total_amount_of_θ,m)

    for func_i = 1:m
        current_col = Vector{Float64}(undef, 0) # Preallocate memory
        for param_i = 1:length(Flux.params(model)) - 1
            jac_vec = jac(model, x, func_i, param_i)[:]
            current_col = vcat(current_col, jac_vec) # Concatenate vectors
        end
        for k = 1:total_amount_of_θ 
            Jacob[k, func_i] = current_col[k]
        end
    end

    return Jacob # Þetta er Df fylkið í bilblíunni
end

Df (generic function with 1 method)

In [356]:
J = Df(model,xn)

J[:,1] == flat_grads[1]

true